export const IS_LOGGED = "IS_LOGGED";
export const IS_LOGGED_OUT = "IS_LOGGED_OUT";
export const GET_INSTRUCTOR = "GET_INSTRUCTOR";
export const GET_COURSE = "GET_COURSE";
export const GET_FEATURED_COURSE = "GET_FEATURED_COURSE";
export const SIGN_UP = "SIGN_UP";
export const ANALYTICS = "ANALYTICS";
export const GET_SELECTED_COURSE_ID = "GET_SELECTED_COURSE_ID";
export const GET_SELECTED_INSTRUCTOR_ID = "GET_SELECTED_INSTRUCTOR_ID";


