export const IS_LOGGED = "IS_LOGGED";
export const IS_LOGGED_OUT = "IS_LOGGED_OUT";
export const GET_INSTRUCTOR = "GET_INSTRUCTOR";
export const POST_INSTRUCTOR = "POST_INSTRUCTOR";
export const UPDATE_INSTRUCTOR = "UPDATE_INSTRUCTOR";
export const GET_COURSE = "GET_COURSE";
export const GET_COURSE_BY_ID = "GET_COURSE_BY_ID";
export const GET_INSTRUCTOR_BY_ID = "GET_INSTRUCTOR_BY_ID";
export const POST_COURSE = "POST_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const GET_FEATURED_COURSE = "GET_FEATURED_COURSE";
export const GET_FEATURED_INSTRUCTOR = "GET_FEATURED_INSTRUCTOR";
export const SIGN_UP = "SIGN_UP";
export const CUPON = "CUPON";
export const GET_CUPON = "GET_CUPON";

export const ANALYTICS = "ANALYTICS";
export const GET_SELECTED_COURSE_ID = "GET_SELECTED_COURSE_ID";
export const GET_SELECTED_INSTRUCTOR_ID = "GET_SELECTED_INSTRUCTOR_ID";
export const GET_SELECTED_LESSON_ID = "GET_SELECTED_LESSON_ID";
export const GET_CATAGORY = "GET_CATAGORY";
export const GET_CART = "GET_CART";
export const POST_CART = "POST_CART";
export const DEL_CART = "DEL_CART";
export const GET_ALL_USER = "GET_ALL_USER";

export const GET_ALL_MESSAGE = "GET_ALL_MESSAGE";
export const POST_MESSAGE = "POST_MESSAGE";
export const REPLY_MESSAGE = "REPLY_MESSAGE";
export const GET_GENERAL_MESSAGE = "GET_GENERAL_MESSAGE";
export const GET_STUDENT_MESSAGE = "GET_STUDENT_MESSAGE";
export const GET_MESSAGE_BY_ID = "GET_MESSAGE_BY_ID";
export const GET_CURRENT_MESSAGE_BY_ID = "GET_CURRENT_MESSAGE_BY_ID";
export const GET_PREVIOUS_MESSAGE_BY_ID = "GET_PREVIOUS_MESSAGE_BY_ID";
export const GET_DYNAMICALLY_BY_TAG = "GET_DYNAMICALLY_BY_TAG";

export const GET_TYPED_USER = "GET_TYPED_USER";

export const GET_TYPED_USER_1 = "  GET_TYPED_USER_1,";
export const GET_TYPED_USER_2 = "  GET_TYPED_USER_2,";
export const GET_TYPED_USER_3 = "  GET_TYPED_USER_3,";
export const GET_TYPED_USER_4 = "  GET_TYPED_USER_4,";
export const GET_TYPED_USER_STUDENT = "  GET_TYPED_USER_STUDENT,";
export const GET_TYPED_USER_SUBSCRIBER = "  GET_TYPED_USER_SUBSCRIBER,";

export const GET_USER_COURSE = "GET_USER_COURSE";
export const SSL_RESPONSE = "SSL_RESPONSE";
export const GET_SELECTED_COURSE_CATEGORY = "GET_SELECTED_COURSE_CATEGORY";
export const GET_WISHLIST_BY_ID = "GET_WISHLIST_BY_ID";
export const POST_WISHLIST = "POST_WISHLIST";
export const USER_UPDATE = "USER_UPDATE";

export const USER_SUSPEND = "USER_SUSPEND";
export const POST_FILTER= "POST_FILTER"
